# Generated by Django 3.1.3 on 2020-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201115_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='todo.Tag'),
        ),
    ]
