# Generated by Django 3.1.3 on 2020-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201115_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Not Important'), (2, 'Important'), (3, 'Urgent')], null=True),
        ),
    ]
