# Generated by Django 3.1.3 on 2020-11-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201116_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_updated',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
